get:
  tags: [server-settings]
  security:
    - cookieAuth: []
  summary: Get feature flags configuration
  operationId: config_get_features
  responses:
    '200':
      description: feature flags config
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/all.yaml#/FeatureFlags'
    '400': { $ref: '../../components/responses.yaml#/BadRequest' }
    '401': { $ref: '../../components/responses.yaml#/Unauthorized' }
    '403': { $ref: '../../components/responses.yaml#/Forbidden' }
    '409': { $ref: '../../components/responses.yaml#/Conflict' }
    '422': { $ref: '../../components/responses.yaml#/ValidationError' }
    '429': { $ref: '../../components/responses.yaml#/RateLimitExceeded' }
    '500': { $ref: '../../components/responses.yaml#/InternalServerError' }
