get:
  tags: [server-settings]
  security:
    - cookieAuth: []
  summary: Get logging configuration
  operationId: config_get_logging
  responses:
    '200':
      description: Logging config
      content:
        application/json:
          schema:
            allOf:
            - $ref: '../../components/schemas/all.yaml#/SuccessEnvelope'
            - type: object
            properties:
                  data: { $ref: '../../components/schemas/all.yaml#/LoggingConfig' }
    '401': { $ref: '../../components/responses.yaml#/Unauthorized' }
    '403': { $ref: '../../components/responses.yaml#/Forbidden' }
    '429': { $ref: '../../components/responses.yaml#/RateLimitExceeded' }
    '500': { $ref: '../../components/responses.yaml#/InternalServerError' }
put:
  tags: [server-settings]
  security:
    - cookieAuth: []
  summary: Update logging configuration
  operationId: config_update_logging
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/all.yaml#/LoggingConfig'
  responses:
    '200':
      description: Updated
      content:
        application/json:
          schema:
            allOf:
            - $ref: '../../components/schemas/all.yaml#/SuccessEnvelope'
            - type: object
            properties:
                  data: { $ref: '../../components/schemas/all.yaml#/LoggingConfig' }
    '400': { $ref: '../../components/responses.yaml#/BadRequest' }
    '401': { $ref: '../../components/responses.yaml#/Unauthorized' }
    '403': { $ref: '../../components/responses.yaml#/Forbidden' }
    '409': { $ref: '../../components/responses.yaml#/Conflict' }
    '422': { $ref: '../../components/responses.yaml#/ValidationError' }
    '429': { $ref: '../../components/responses.yaml#/RateLimitExceeded' }
    '500': { $ref: '../../components/responses.yaml#/InternalServerError' }
