get:
  tags: [server-settings]
  security:
    - cookieAuth: []
  summary: Get worker configuration
  operationId: config_get_worker
  responses:
    '200':
      description: worker config
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../../components/schemas/all.yaml#/SuccessEnvelope'
              - type: object
                properties:
                  data:
                    $ref: '../../components/schemas/all.yaml#/WorkerConfig'
    '401': { $ref: '../../components/responses.yaml#/Unauthorized' }
    '403': { $ref: '../../components/responses.yaml#/Forbidden' }
    '429': { $ref: '../../components/responses.yaml#/RateLimitExceeded' }
    '500': { $ref: '../../components/responses.yaml#/InternalServerError' }
put:
  tags: [server-settings]
  security:
    - cookieAuth: []
  summary: Update worker configuration
  operationId: config_update_worker
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/all.yaml#/WorkerConfig'
  responses:
    '200':
      description: Updated
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../../components/schemas/all.yaml#/SuccessEnvelope'
              - type: object
                properties:
                  data:
                    $ref: '../../components/schemas/all.yaml#/WorkerConfig'
    '400': { $ref: '../../components/responses.yaml#/BadRequest' }
    '401': { $ref: '../../components/responses.yaml#/Unauthorized' }
    '403': { $ref: '../../components/responses.yaml#/Forbidden' }
    '409': { $ref: '../../components/responses.yaml#/Conflict' }
    '422': { $ref: '../../components/responses.yaml#/ValidationError' }
    '429': { $ref: '../../components/responses.yaml#/RateLimitExceeded' }
    '500': { $ref: '../../components/responses.yaml#/InternalServerError' }